Rename vManage to Manager

diff --git a/roles/azure_controllers/templates/userdata_manager.j2 b/roles/azure_controllers/templates/userdata_manager.j2
--- a/roles/azure_controllers/templates/userdata_manager.j2
+++ b/roles/azure_controllers/templates/userdata_manager.j2
@@ -10,45 +10,25 @@ Content-Disposition: attachment; filename="cloud-config"
 
 #cloud-config
 
-chpasswd:
-  expire: false
-  list:
-  - root:root
-  - {{ admin_username }}:{{ admin_password }}
 disk_setup:
-{% if cloud_provider == 'aws' %}
-  /dev/nvme1n1:
-{% endif %}
-{% if cloud_provider == 'azure' %}
   /dev/disk/azure/scsi1/lun10:
-{% endif %}
     table_type: mbr
     layout: false
     overwrite: false
 fs_setup:
-{% if cloud_provider == 'aws' %}
-- device: /dev/nvme1n1
-{% endif %}
-{% if cloud_provider == 'azure' %}
 - device: /dev/disk/azure/scsi1/lun10
-{% endif %}
   label: data
   partition: none
   filesystem: ext4
   overwrite: false
 mounts:
-{% if cloud_provider == 'aws' %}
-- [ /dev/nvme1n1, /opt/data ]
-{% endif %}
-{% if cloud_provider == 'azure' %}
 - [ /dev/disk/azure/scsi1/lun10, /opt/data ]
-{% endif %}
 
 write_files:
 - path: /opt/web-app/etc/persona
   owner: vmanage:vmanage-admin
   permissions: '0644'
-  content: '{"persona":"COMPUTE_AND_DATA"}'
+  content: '{"persona":"{{ manager_persona }}"}'
 - path: /etc/default/personality
   content: "vmanage\n"
 - path: /etc/default/inited
@@ -63,7 +43,7 @@ write_files:
         <system-ip>{{ system_ip }}</system-ip>
         <organization-name>{{ organization_name }}</organization-name>
         <sp-organization-name>{{ organization_name }}</sp-organization-name>
-        <site-id>{{ site_id_vmanage }}</site-id>
+        <site-id>{{ site_id }}</site-id>
         <vbond>
           <remote>{{ vbond_transport_public_ip | default(default_vbond_ip) }}</remote>
         </vbond>
@@ -72,7 +52,7 @@ write_files:
           <auth-order>radius</auth-order>
           <auth-order>tacacs</auth-order>
           <user>
-            <name>admin</name>
+            <name>{{ admin_username }}</name>
             <password>{{ admin_password }}</password>
             <group>netadmin</group>
           </user>
@@ -99,7 +79,6 @@ write_files:
               </tunnel-interface>
               <shutdown>false</shutdown>
             </interface>
-{% if cloud_provider == 'azure' %}
           <ip>
             <route>
               <prefix>0.0.0.0/0</prefix>
@@ -108,7 +87,6 @@ write_files:
               </next-hop>
             </route>
           </ip>
-{% endif %}
         </vpn-instance>
         <vpn-instance>
           <vpn-id>512</vpn-id>
@@ -122,4 +100,76 @@ write_files:
         </vpn-instance>
       </vpn>
     </config>
+
+{% if manager_cluster_private_ip is defined %}
+- path: /home/admin/customized.cfg
+  content: |
+    vpn 0
+        interface eth2
+            ip address {{ manager_cluster_private_ip }}/{{ manager_cluster_prefix }}
+            no shutdown
+        !
+    !
+
+bootcmd:
+  - |
+    cat << 'EOF' > /etc/customized.sh
+    #!/bin/bash
+    MAX_WAIT=1800
+    WAIT_TIMER=30
+    MAX_RETRY=20
+    RETRY_TIMER=5
+
+    success_file_name=/home/admin/success.log
+    failure_file_name=/home/admin/failure.log
+
+    start_time=`date +%s`
+    while true
+    do
+        end_time=`date +%s`
+
+        CONFD_IPC_ACCESS_FILE="/etc/confd/confd_ipc_secret"
+        cloud_init_rerun="/home/admin/customized.cfg"
+        export CONFD_IPC_ACCESS_FILE=/etc/confd/confd_ipc_secret
+
+        if [ -f "$CONFD_IPC_ACCESS_FILE" ] && [ -f "$cloud_init_rerun" ];then
+            sleep $WAIT_TIMER
+
+            break_flap=0
+            for retry_timer in `seq $MAX_RETRY`
+            do
+              confd_load -H -dd -lm -e -F c $cloud_init_rerun >> "$success_file_name" 2>&1
+              if [ $? -eq 0 ];then
+                echo success >> "$success_file_name"
+                mv $cloud_init_rerun ${cloud_init_rerun}.bak
+                break_flap=1
+                break
+              fi
+              sleep $RETRY_TIMER
+              echo "Retry: $retry_timer" >> "$success_file_name"
+            done
+
+            if [ $break_flap -eq 0 ];then
+              echo "Load configure error" >> "$success_file_name"
+            else
+              echo "Load configure success" >> "$success_file_name"
+            fi
+
+            break
+        fi
+
+        if [ $((end_time - start_time)) -gt $MAX_WAIT ];then
+            echo "start_time: $start_time" >> "$failure_file_name"
+            echo "end_time: $end_time" >> "$failure_file_name"
+            echo "end_time - start_time: $((end_time - start_time))" >> "$failure_file_name"
+            echo "MAX_WAIT: $MAX_WAIT" >> "$failure_file_name"
+            break
+        fi;
+
+        sleep 0.1
+
+    done
+    EOF
+  - (nohup bash /etc/customized.sh >> /home/admin/customized_config.log 2>&1 )&
+{% endif %}
 --===============8815267485200512281==
